### ISSUE TITLE
Add QA Bot (JellyChat) to Wiki

### ISSUE THREAD

**Issue by 0ptim** [0ptim/DeFiChain-Wiki#80]
### First prototype
- [x] Add new page where user can ask question and becomes an answer.
- [x] Improve UI for first internal version.
- [x] Add `Info` button which informs user about the bot (Limitations, how can they help improve, link to contribution guide, etc.)
- [x] Make UI work for light/dark-mode.
- [x] Optimize for mobile.
- [x] Bot documentation pages for German and Turkish.
- [x] JellyChat translation for German and Turkish.

### When prototype finished
- [x] Add direct link for the new page to the `navbar` and to the home page.

### Notes & Ideas
- Get in touch with Ben from the Accelerator team to check on Jelly-Usage terms.
- Collaborate with Iris on potential Images/Animation work.
